__title__ = "versionbump"
__version__ = "1.0.2"
__desc__ = "Search and replace version information by whole string or field."
__author__ = "Mike Pento"
__email__ = "mpento@darkforge.net"
__copyright__ = "Copyright (c) 2024"
__license__ = "GPL"
